export interface ImcAdultoReq{
    peso: number
    altura: number
}

export interface ImcIdosoReq{
    peso: number
    altura: number
}

export interface ImcGestanteReq{
    peso: number
    altura: number
    semanaGestacional: number
}

export class ImcService{
    public imcAdulto(data: ImcAdultoReq){
           
        let dataRegistro = new Date()
        let altura = data.altura
        let peso = data.peso
        let imc: number = parseFloat((peso / (altura * altura)).toFixed(2))
        let pesoIdealMin = parseFloat((18.5 * Math.pow(altura, 2)).toFixed(2))
        let pesoIdealMax = parseFloat((24.99 * Math.pow(altura, 2)).toFixed(2))

       const classificacao = this.classificacaoAdulto(imc)

       return {
            imc,
            peso,
            altura,
            dataRegistro: dataRegistro,
            classificacao: classificacao,
            pesoIdealMin: pesoIdealMin,
            pesoIdealMax: pesoIdealMax,
       }
    }

    public imcIdoso(data: ImcIdosoReq){
        let dataRegistro = new Date()
        let altura = data.altura
        let peso = data.peso
        let imc: number = parseFloat((peso / (altura * altura)).toFixed(2))
        let pesoIdealMin = parseFloat((22.01 * Math.pow(altura, 2)).toFixed(2))
        let pesoIdealMax = parseFloat((26.99 * Math.pow(altura, 2)).toFixed(2))

        const classificacao = this.classificacaoIdoso(imc)

        return {
            imc,
            peso,
            altura,
            dataRegistro: dataRegistro,
            classificacao: classificacao,
            pesoIdealMin: pesoIdealMin,
            pesoIdealMax: pesoIdealMax,
        }
    }

    public imcGestante(data: ImcGestanteReq){
        let dataRegistro = new Date()
        let semanaGestacional = data.semanaGestacional
        let altura = data.altura
        let peso = data.peso
        let imc: number = parseFloat((peso / (altura * altura)).toFixed(2))
        
        const {classificacao, pesoIdealMin, pesoIdealMax} = this.classificacaoGestante(imc, semanaGestacional, altura)

        return {
            imc,
            peso,
            altura,
            semanaGestacional,
            dataRegistro: dataRegistro,
            classificacao: classificacao,
            pesoIdealMin: pesoIdealMin,
            pesoIdealMax: pesoIdealMax,
        }
    }

    private classificacaoAdulto(valor: number){
        let listaClassificacao = []
        listaClassificacao = this.listaClassificacaoAdulto()
        let classificacao = listaClassificacao.find(v => valor >= v.valorInicio && valor <= v.valorFim)

        return classificacao?.classificacao
    }

    private classificacaoIdoso(valor: number){
        let listaClassificacao = []
        listaClassificacao = this.listaClassificacaoIdoso()
        let classificacao = listaClassificacao.find(v => valor >= v.valorInicio && valor <= v.valorFim)

        return classificacao?.classificacao
    }

    private classificacaoGestante(valor: number, semanaGestacional: number, altura: number,){
        let listaClassificacao = []
        
        listaClassificacao = this.listaClassificacaoGestante()
        let lista = listaClassificacao.filter(v => v.semanaGestacional === semanaGestacional)
        let classificacao = lista.find(v => valor >= v.valorInicio && valor <= v.valorFim)

        let imcIdeal = lista.find(v => /NORMAL$/.test(v.codigo))
        let valorInicio = imcIdeal?.valorInicio || 0
        let valorFim = imcIdeal?.valorFim || 0
        let pesoIdealMin = parseFloat((valorInicio * Math.pow(altura, 2)).toFixed(2))
        let pesoIdealMax = parseFloat((valorFim * Math.pow(altura, 2)).toFixed(2))

        return {
            classificacao: classificacao?.classificacao,
            pesoIdealMin,
            pesoIdealMax,
        }
    }

    private listaClassificacaoAdulto(){
        return [
            {
                codigo: "IMC_ADULTO_MUITO_ABAIXO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 0,
                valorFim: 16.99,
                classificacao: "Muito abaixo do peso"
            },
            {
                codigo: "IMC_ADULTO_ABAIXO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 17,
                valorFim: 18.49,
                classificacao: "Abaixo do peso"
            },
            {
                codigo: "IMC_ADULTO_NORMAL",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 18.5,
                valorFim: 24.99,
                classificacao: "Peso normal"
            },
            {
                codigo: "IMC_ADULTO_ACIMA",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 25,
                valorFim: 29.99,
                classificacao: "Acima do peso"
            },
            {
                codigo: "IMC_ADULTO_OBESIDADE1",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 30,
                valorFim: 34.99,
                classificacao: "Obesidade 1"
            },
            {
                codigo: "IMC_ADULTO_OBESIDADE2",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 35,
                valorFim: 39.99,
                classificacao: "Obesidade 2"
            },
            {
                codigo: "IMC_ADULTO_OBESIDADE3",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 40,
                valorFim: 999,
                classificacao: "Obesidade 3 (mórbida)"
            }
        ]
    }

    private listaClassificacaoIdoso(){
        return [
            {
                codigo: "IMC_IDOSO_BAIXO_PESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 0,
                valorFim: 22,
                classificacao: "Baixo peso"
            },
            {
                codigo: "IMC_IDOSO_ADEQUADO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 22.01,
                valorFim: 26.99,
                classificacao: "Adequado ou eutrófico"
            },
            {
                codigo: "IMC_IDOSO_SOBREPESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 27,
                valorFim: 999,
                classificacao: "Sobrepeso"
            }
        ]
    }

    private listaClassificacaoGestante(){
        return [
            {
                codigo: "IMC_GESTANTE_6_BAIXO_PESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 0,
                valorFim: 19.9,
                classificacao: "Baixo Peso",
                semanaGestacional: 6,
            },
            {
                codigo: "IMC_GESTANTE_6_NORMAL",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 20,
                valorFim: 24.9,
                classificacao: "Normal",
                semanaGestacional: 6,
            },
            {
                codigo: "IMC_GESTANTE_6_SOBREPESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 25,
                valorFim: 30,
                classificacao: "Sobrepeso",
                semanaGestacional: 6,
            },
            {
                codigo: "IMC_GESTANTE_6_OBESIDADE",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 30.1,
                valorFim: 999,
                classificacao: "Obesidade",
                semanaGestacional: 6,
            },
            {
                codigo: "IMC_GESTANTE_8_BAIXO_PESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 0,
                valorFim: 20.1,
                classificacao: "Baixo Peso",
                semanaGestacional: 8,
            },
            {
                codigo: "IMC_GESTANTE_8_NORMAL",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 20.2,
                valorFim: 25,
                classificacao: "Normal",
                semanaGestacional: 8,
            },
            {
                codigo: "IMC_GESTANTE_8_SOBREPESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 25.1,
                valorFim: 30.1,
                classificacao: "Sobrepeso",
                semanaGestacional: 8,
            },
            {
                codigo: "IMC_GESTANTE_8_OBESIDADE",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 30.2,
                valorFim: 999,
                classificacao: "Obesidade",
                semanaGestacional: 8,
            },
            {
                codigo: "IMC_GESTANTE_10_BAIXO_PESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 0,
                valorFim: 20.2,
                classificacao: "Baixo Peso",
                semanaGestacional: 10,
            },
            {
                codigo: "IMC_GESTANTE_10_NORMAL",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 20.3,
                valorFim: 25.2,
                classificacao: "Normal",
                semanaGestacional: 10,
            },
            {
                codigo: "IMC_GESTANTE_10_SOBREPESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 25.3,
                valorFim: 30.2,
                classificacao: "Sobrepeso",
                semanaGestacional: 10,
            },
            {
                codigo: "IMC_GESTANTE_10_OBESIDADE",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 30.3,
                valorFim: 999,
                classificacao: "Obesidade",
                semanaGestacional: 10,
            },
            {
                codigo: "IMC_GESTANTE_11_BAIXO_PESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 0,
                valorFim: 20.3,
                classificacao: "Baixo Peso",
                semanaGestacional: 11,
            },
            {
                codigo: "IMC_GESTANTE_11_NORMAL",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 20.4,
                valorFim: 25.3,
                classificacao: "Normal",
                semanaGestacional: 11,
            },
            {
                codigo: "IMC_GESTANTE_11_SOBREPESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 25.4,
                valorFim: 30.3,
                classificacao: "Sobrepeso",
                semanaGestacional: 11,
            },
            {
                codigo: "IMC_GESTANTE_11_OBESIDADE",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 30.4,
                valorFim: 999,
                classificacao: "Obesidade",
                semanaGestacional: 11,
            },
            {
                codigo: "IMC_GESTANTE_12_BAIXO_PESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 0,
                valorFim: 20.4,
                classificacao: "Baixo Peso",
                semanaGestacional: 12,
            },
            {
                codigo: "IMC_GESTANTE_12_NORMAL",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 20.5,
                valorFim: 25.4,
                classificacao: "Normal",
                semanaGestacional: 12,
            },
            {
                codigo: "IMC_GESTANTE_12_SOBREPESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 25.5,
                valorFim: 30.3,
                classificacao: "Sobrepeso",
                semanaGestacional: 12,
            },
            {
                codigo: "IMC_GESTANTE_12_OBESIDADE",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 30.4,
                valorFim: 999,
                classificacao: "Obesidade",
                semanaGestacional: 12,
            },
            {
                codigo: "IMC_GESTANTE_13_BAIXO_PESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 0,
                valorFim: 20.6,
                classificacao: "Baixo Peso",
                semanaGestacional: 13,
            },
            {
                codigo: "IMC_GESTANTE_13_NORMAL",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 20.7,
                valorFim: 25.6,
                classificacao: "Normal",
                semanaGestacional: 13,
            },
            {
                codigo: "IMC_GESTANTE_13_SOBREPESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 25.7,
                valorFim: 30.4,
                classificacao: "Sobrepeso",
                semanaGestacional: 13,
            },
            {
                codigo: "IMC_GESTANTE_13_OBESIDADE",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 30.5,
                valorFim: 999,
                classificacao: "Obesidade",
                semanaGestacional: 13,
            },
            {
                codigo: "IMC_GESTANTE_14_BAIXO_PESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 0,
                valorFim: 20.7,
                classificacao: "Baixo Peso",
                semanaGestacional: 14,
            },
            {
                codigo: "IMC_GESTANTE_14_NORMAL",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 20.8,
                valorFim: 25.7,
                classificacao: "Normal",
                semanaGestacional: 14,
            },
            {
                codigo: "IMC_GESTANTE_14_SOBREPESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 25.8,
                valorFim: 30.5,
                classificacao: "Sobrepeso",
                semanaGestacional: 14,
            },
            {
                codigo: "IMC_GESTANTE_14_OBESIDADE",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 30.6,
                valorFim: 999,
                classificacao: "Obesidade",
                semanaGestacional: 14,
            },
            {
                codigo: "IMC_GESTANTE_15_BAIXO_PESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 0,
                valorFim: 20.8,
                classificacao: "Baixo Peso",
                semanaGestacional: 15,
            },
            {
                codigo: "IMC_GESTANTE_15_NORMAL",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 20.9,
                valorFim: 25.8,
                classificacao: "Normal",
                semanaGestacional: 15,
            },
            {
                codigo: "IMC_GESTANTE_15_SOBREPESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 25.9,
                valorFim: 30.6,
                classificacao: "Sobrepeso",
                semanaGestacional: 15,
            },
            {
                codigo: "IMC_GESTANTE_15_OBESIDADE",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 30.7,
                valorFim: 999,
                classificacao: "Obesidade",
                semanaGestacional: 15,
            },
            {
                codigo: "IMC_GESTANTE_16_BAIXO_PESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 0,
                valorFim: 21,
                classificacao: "Baixo Peso",
                semanaGestacional: 16,
            },
            {
                codigo: "IMC_GESTANTE_16_NORMAL",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 21.1,
                valorFim: 25.9,
                classificacao: "Normal",
                semanaGestacional: 16,
            },
            {
                codigo: "IMC_GESTANTE_16_SOBREPESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 26,
                valorFim: 30.7,
                classificacao: "Sobrepeso",
                semanaGestacional: 16,
            },
            {
                codigo: "IMC_GESTANTE_16_OBESIDADE",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 30.8,
                valorFim: 999,
                classificacao: "Obesidade",
                semanaGestacional: 16,
            },
            {
                codigo: "IMC_GESTANTE_17_BAIXO_PESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 0,
                valorFim: 21.1,
                classificacao: "Baixo Peso",
                semanaGestacional: 17,
            },
            {
                codigo: "IMC_GESTANTE_17_NORMAL",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 21.2,
                valorFim: 26,
                classificacao: "Normal",
                semanaGestacional: 17,
            },
            {
                codigo: "IMC_GESTANTE_17_SOBREPESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 26.1,
                valorFim: 30.8,
                classificacao: "Sobrepeso",
                semanaGestacional: 17,
            },
            {
                codigo: "IMC_GESTANTE_17_OBESIDADE",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 30.9,
                valorFim: 999,
                classificacao: "Obesidade",
                semanaGestacional: 17,
            },
            {
                codigo: "IMC_GESTANTE_18_BAIXO_PESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 0,
                valorFim: 21.2,
                classificacao: "Baixo Peso",
                semanaGestacional: 18,
            },
            {
                codigo: "IMC_GESTANTE_18_NORMAL",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 21.3,
                valorFim: 26.1,
                classificacao: "Normal",
                semanaGestacional: 18,
            },
            {
                codigo: "IMC_GESTANTE_18_SOBREPESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 26.2,
                valorFim: 30.9,
                classificacao: "Sobrepeso",
                semanaGestacional: 18,
            },
            {
                codigo: "IMC_GESTANTE_18_OBESIDADE",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 31,
                valorFim: 999,
                classificacao: "Obesidade",
                semanaGestacional: 18,
            },
            {
                codigo: "IMC_GESTANTE_19_BAIXO_PESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 0,
                valorFim: 21.4,
                classificacao: "Baixo Peso",
                semanaGestacional: 19,
            },
            {
                codigo: "IMC_GESTANTE_19_NORMAL",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 21.5,
                valorFim: 26.2,
                classificacao: "Normal",
                semanaGestacional: 19,
            },
            {
                codigo: "IMC_GESTANTE_19_SOBREPESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 26.3,
                valorFim: 30.9,
                classificacao: "Sobrepeso",
                semanaGestacional: 19,
            },
            {
                codigo: "IMC_GESTANTE_19_OBESIDADE",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 31,
                valorFim: 999,
                classificacao: "Obesidade",
                semanaGestacional: 19,
            },
            {
                codigo: "IMC_GESTANTE_20_BAIXO_PESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 0,
                valorFim: 21.5,
                classificacao: "Baixo Peso",
                semanaGestacional: 20,
            },
            {
                codigo: "IMC_GESTANTE_20_NORMAL",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 21.6,
                valorFim: 26.3,
                classificacao: "Normal",
                semanaGestacional: 20,
            },
            {
                codigo: "IMC_GESTANTE_20_SOBREPESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 26.4,
                valorFim: 31,
                classificacao: "Sobrepeso",
                semanaGestacional: 20,
            },
            {
                codigo: "IMC_GESTANTE_20_OBESIDADE",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 31.1,
                valorFim: 999,
                classificacao: "Obesidade",
                semanaGestacional: 20,
            },
            {
                codigo: "IMC_GESTANTE_21_BAIXO_PESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 0,
                valorFim: 21.7,
                classificacao: "Baixo Peso",
                semanaGestacional: 21,
            },
            {
                codigo: "IMC_GESTANTE_21_NORMAL",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 21.8,
                valorFim: 26.4,
                classificacao: "Normal",
                semanaGestacional: 21,
            },
            {
                codigo: "IMC_GESTANTE_21_SOBREPESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 26.5,
                valorFim: 31.1,
                classificacao: "Sobrepeso",
                semanaGestacional: 21,
            },
            {
                codigo: "IMC_GESTANTE_21_OBESIDADE",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 31.2,
                valorFim: 999,
                classificacao: "Obesidade",
                semanaGestacional: 21,
            },
            {
                codigo: "IMC_GESTANTE_22_BAIXO_PESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 0,
                valorFim: 21.8,
                classificacao: "Baixo Peso",
                semanaGestacional: 22,
            },
            {
                codigo: "IMC_GESTANTE_22_NORMAL",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 21.9,
                valorFim: 26.6,
                classificacao: "Normal",
                semanaGestacional: 22,
            },
            {
                codigo: "IMC_GESTANTE_22_SOBREPESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 26.7,
                valorFim: 31.2,
                classificacao: "Sobrepeso",
                semanaGestacional: 22,
            },
            {
                codigo: "IMC_GESTANTE_22_OBESIDADE",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 31.3,
                valorFim: 999,
                classificacao: "Obesidade",
                semanaGestacional: 22,
            },
            {
                codigo: "IMC_GESTANTE_23_BAIXO_PESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 0,
                valorFim: 22,
                classificacao: "Baixo Peso",
                semanaGestacional: 23,
            },
            {
                codigo: "IMC_GESTANTE_23_NORMAL",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 22.1,
                valorFim: 26.8,
                classificacao: "Normal",
                semanaGestacional: 23,
            },
            {
                codigo: "IMC_GESTANTE_23_SOBREPESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 26.9,
                valorFim: 31.3,
                classificacao: "Sobrepeso",
                semanaGestacional: 23,
            },
            {
                codigo: "IMC_GESTANTE_23_OBESIDADE",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 31.4,
                valorFim: 999,
                classificacao: "Obesidade",
                semanaGestacional: 23,
            },
            {
                codigo: "IMC_GESTANTE_24_BAIXO_PESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 0,
                valorFim: 22.2,
                classificacao: "Baixo Peso",
                semanaGestacional: 24,
            },
            {
                codigo: "IMC_GESTANTE_24_NORMAL",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 22.3,
                valorFim: 26.9,
                classificacao: "Normal",
                semanaGestacional: 24,
            },
            {
                codigo: "IMC_GESTANTE_24_SOBREPESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 27,
                valorFim: 31.5,
                classificacao: "Sobrepeso",
                semanaGestacional: 24,
            },
            {
                codigo: "IMC_GESTANTE_24_OBESIDADE",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 31.6,
                valorFim: 999,
                classificacao: "Obesidade",
                semanaGestacional: 24,
            },
            {
                codigo: "IMC_GESTANTE_25_BAIXO_PESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 0,
                valorFim: 22.4,
                classificacao: "Baixo Peso",
                semanaGestacional: 25,
            },
            {
                codigo: "IMC_GESTANTE_25_NORMAL",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 22.5,
                valorFim: 27,
                classificacao: "Normal",
                semanaGestacional: 25,
            },
            {
                codigo: "IMC_GESTANTE_25_OBESIDADE",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 31.7,
                valorFim: 999,
                classificacao: "Obesidade",
                semanaGestacional: 25,
            },
            {
                codigo: "IMC_GESTANTE_26_BAIXO_PESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 0,
                valorFim: 22.6,
                classificacao: "Baixo Peso",
                semanaGestacional: 26,
            },
            {
                codigo: "IMC_GESTANTE_26_NORMAL",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 22.7,
                valorFim: 27.2,
                classificacao: "Normal",
                semanaGestacional: 26,
            },
            {
                codigo: "IMC_GESTANTE_26_SOBREPESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 27.3,
                valorFim: 31.7,
                classificacao: "Sobrepeso",
                semanaGestacional: 26,
            },
            {
                codigo: "IMC_GESTANTE_26_OBESIDADE",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 31.8,
                valorFim: 999,
                classificacao: "Obesidade",
                semanaGestacional: 26,
            },
            {
                codigo: "IMC_GESTANTE_27_BAIXO_PESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 0,
                valorFim: 22.7,
                classificacao: "Baixo Peso",
                semanaGestacional: 27,
            },
            {
                codigo: "IMC_GESTANTE_27_NORMAL",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 22.8,
                valorFim: 27.3,
                classificacao: "Normal",
                semanaGestacional: 27,
            },
            {
                codigo: "IMC_GESTANTE_27_SOBREPESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 27.4,
                valorFim: 31.8,
                classificacao: "Sobrepeso",
                semanaGestacional: 27,
            },
            {
                codigo: "IMC_GESTANTE_27_OBESIDADE",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 31.9,
                valorFim: 999,
                classificacao: "Obesidade",
                semanaGestacional: 27,
            },
            {
                codigo: "IMC_GESTANTE_28_BAIXO_PESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 0,
                valorFim: 22.9,
                classificacao: "Baixo Peso",
                semanaGestacional: 28,
            },
            {
                codigo: "IMC_GESTANTE_28_OBESIDADE",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 32,
                valorFim: 999,
                classificacao: "Obesidade",
                semanaGestacional: 28,
            },
            {
                codigo: "IMC_GESTANTE_28_NORMAL",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 23,
                valorFim: 27.5,
                classificacao: "Normal",
                semanaGestacional: 28,
            },
            {
                codigo: "IMC_GESTANTE_28_SOBREPESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 27.6,
                valorFim: 31.9,
                classificacao: "Sobrepeso",
                semanaGestacional: 28,
            },
            {
                codigo: "IMC_GESTANTE_29_BAIXO_PESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 0,
                valorFim: 23.1,
                classificacao: "Baixo Peso",
                semanaGestacional: 29,
            },
            {
                codigo: "IMC_GESTANTE_29_NORMAL",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 23.2,
                valorFim: 27.6,
                classificacao: "Normal",
                semanaGestacional: 29,
            },
            {
                codigo: "IMC_GESTANTE_29_SOBREPESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 27.7,
                valorFim: 32,
                classificacao: "Sobrepeso",
                semanaGestacional: 29,
            },
            {
                codigo: "IMC_GESTANTE_29_OBESIDADE",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 32.1,
                valorFim: 999,
                classificacao: "Obesidade",
                semanaGestacional: 29,
            },
            {
                codigo: "IMC_GESTANTE_30_BAIXO_PESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 0,
                valorFim: 23.3,
                classificacao: "Baixo Peso",
                semanaGestacional: 30,
            },
            {
                codigo: "IMC_GESTANTE_30_NORMAL",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 23.4,
                valorFim: 27.8,
                classificacao: "Normal",
                semanaGestacional: 30,
            },
            {
                codigo: "IMC_GESTANTE_30_SOBREPESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 27.9,
                valorFim: 32.1,
                classificacao: "Sobrepeso",
                semanaGestacional: 30,
            },
            {
                codigo: "IMC_GESTANTE_30_OBESIDADE",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 32.2,
                valorFim: 999,
                classificacao: "Obesidade",
                semanaGestacional: 30,
            },
            {
                codigo: "IMC_GESTANTE_31_BAIXO_PESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 0,
                valorFim: 23.4,
                classificacao: "Baixo Peso",
                semanaGestacional: 31,
            },
            {
                codigo: "IMC_GESTANTE_31_NORMAL",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 23.5,
                valorFim: 27.9,
                classificacao: "Normal",
                semanaGestacional: 31,
            },
            {
                codigo: "IMC_GESTANTE_31_SOBREPESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 28,
                valorFim: 32.2,
                classificacao: "Sobrepeso",
                semanaGestacional: 31,
            },
            {
                codigo: "IMC_GESTANTE_31_OBESIDADE",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 32.3,
                valorFim: 999,
                classificacao: "Obesidade",
                semanaGestacional: 31,
            },
            {
                codigo: "IMC_GESTANTE_32_BAIXO_PESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 0,
                valorFim: 23.6,
                classificacao: "Baixo Peso",
                semanaGestacional: 32,
            },
            {
                codigo: "IMC_GESTANTE_32_NORMAL",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 23.7,
                valorFim: 28,
                classificacao: "Normal",
                semanaGestacional: 32,
            },
            {
                codigo: "IMC_GESTANTE_32_SOBREPESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 28.1,
                valorFim: 32.3,
                classificacao: "Sobrepeso",
                semanaGestacional: 32,
            },
            {
                codigo: "IMC_GESTANTE_32_OBESIDADE",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 32.4,
                valorFim: 999,
                classificacao: "Obesidade",
                semanaGestacional: 32,
            },
            {
                codigo: "IMC_GESTANTE_33_BAIXO_PESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 0,
                valorFim: 23.8,
                classificacao: "Baixo Peso",
                semanaGestacional: 33,
            },
            {
                codigo: "IMC_GESTANTE_33_NORMAL",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 23.9,
                valorFim: 28.1,
                classificacao: "Normal",
                semanaGestacional: 33,
            },
            {
                codigo: "IMC_GESTANTE_33_SOBREPESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 28.2,
                valorFim: 32.4,
                classificacao: "Sobrepeso",
                semanaGestacional: 33,
            },
            {
                codigo: "IMC_GESTANTE_33_OBESIDADE",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 32.5,
                valorFim: 999,
                classificacao: "Obesidade",
                semanaGestacional: 33,
            },
            {
                codigo: "IMC_GESTANTE_34_BAIXO_PESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 0,
                valorFim: 23.9,
                classificacao: "Baixo Peso",
                semanaGestacional: 34,
            },
            {
                codigo: "IMC_GESTANTE_34_NORMAL",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 24,
                valorFim: 28.3,
                classificacao: "Normal",
                semanaGestacional: 34,
            },
            {
                codigo: "IMC_GESTANTE_34_SOBREPESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 28.4,
                valorFim: 32.5,
                classificacao: "Sobrepeso",
                semanaGestacional: 34,
            },
            {
                codigo: "IMC_GESTANTE_34_OBESIDADE",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 32.6,
                valorFim: 999,
                classificacao: "Obesidade",
                semanaGestacional: 34,
            },
            {
                codigo: "IMC_GESTANTE_35_BAIXO_PESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 0,
                valorFim: 24.1,
                classificacao: "Baixo Peso",
                semanaGestacional: 35,
            },
            {
                codigo: "IMC_GESTANTE_35_NORMAL",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 24.2,
                valorFim: 28.4,
                classificacao: "Normal",
                semanaGestacional: 35,
            },
            {
                codigo: "IMC_GESTANTE_35_SOBREPESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 28.5,
                valorFim: 32.6,
                classificacao: "Sobrepeso",
                semanaGestacional: 35,
            },
            {
                codigo: "IMC_GESTANTE_35_OBESIDADE",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 32.7,
                valorFim: 999,
                classificacao: "Obesidade",
                semanaGestacional: 35,
            },
            {
                codigo: "IMC_GESTANTE_36_BAIXO_PESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 0,
                valorFim: 24.2,
                classificacao: "Baixo Peso",
                semanaGestacional: 36,
            },
            {
                codigo: "IMC_GESTANTE_36_NORMAL",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 24.3,
                valorFim: 28.5,
                classificacao: "Normal",
                semanaGestacional: 36,
            },
            {
                codigo: "IMC_GESTANTE_36_SOBREPESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 28.6,
                valorFim: 32.7,
                classificacao: "Sobrepeso",
                semanaGestacional: 36,
            },
            {
                codigo: "IMC_GESTANTE_36_OBESIDADE",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 32.8,
                valorFim: 999,
                classificacao: "Obesidade",
                semanaGestacional: 36,
            },
            {
                codigo: "IMC_GESTANTE_37_BAIXO_PESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 0,
                valorFim: 24.4,
                classificacao: "Baixo Peso",
                semanaGestacional: 37,
            },
            {
                codigo: "IMC_GESTANTE_37_NORMAL",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 24.5,
                valorFim: 28.7,
                classificacao: "Normal",
                semanaGestacional: 37,
            },
            {
                codigo: "IMC_GESTANTE_37_SOBREPESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 28.8,
                valorFim: 32.8,
                classificacao: "Sobrepeso",
                semanaGestacional: 37,
            },
            {
                codigo: "IMC_GESTANTE_37_OBESIDADE",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 32.9,
                valorFim: 999,
                classificacao: "Obesidade",
                semanaGestacional: 37,
            },
            {
                codigo: "IMC_GESTANTE_38_BAIXO_PESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 0,
                valorFim: 24.5,
                classificacao: "Baixo Peso",
                semanaGestacional: 38,
            },
            {
                codigo: "IMC_GESTANTE_38_NORMAL",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 24.6,
                valorFim: 28.8,
                classificacao: "Normal",
                semanaGestacional: 38,
            },
            {
                codigo: "IMC_GESTANTE_38_SOBREPESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 28.9,
                valorFim: 32.9,
                classificacao: "Sobrepeso",
                semanaGestacional: 38,
            },
            {
                codigo: "IMC_GESTANTE_38_OBESIDADE",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 33,
                valorFim: 999,
                classificacao: "Obesidade",
                semanaGestacional: 38,
            },
            {
                codigo: "IMC_GESTANTE_39_BAIXO_PESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 0,
                valorFim: 24.7,
                classificacao: "Baixo Peso",
                semanaGestacional: 39,
            },
            {
                codigo: "IMC_GESTANTE_39_NORMAL",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 24.8,
                valorFim: 28.9,
                classificacao: "Normal",
                semanaGestacional: 39,
            },
            {
                codigo: "IMC_GESTANTE_39_SOBREPESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 29,
                valorFim: 33,
                classificacao: "Sobrepeso",
                semanaGestacional: 39,
            },
            {
                codigo: "IMC_GESTANTE_39_OBESIDADE",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 33.1,
                valorFim: 999,
                classificacao: "Obesidade",
                semanaGestacional: 39,
            },
            {
                codigo: "IMC_GESTANTE_40_BAIXO_PESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 0,
                valorFim: 24.9,
                classificacao: "Baixo Peso",
                semanaGestacional: 40,
            },
            {
                codigo: "IMC_GESTANTE_40_NORMAL",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 25,
                valorFim: 29.1,
                classificacao: "Normal",
                semanaGestacional: 40,
            },
            {
                codigo: "IMC_GESTANTE_40_SOBREPESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 29.2,
                valorFim: 33.1,
                classificacao: "Sobrepeso",
                semanaGestacional: 40,
            },
            {
                codigo: "IMC_GESTANTE_40_OBESIDADE",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 33.2,
                valorFim: 999,
                classificacao: "Obesidade",
                semanaGestacional: 40,
            },
            {
                codigo: "IMC_GESTANTE_41_BAIXO_PESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 0,
                valorFim: 25,
                classificacao: "Baixo Peso",
                semanaGestacional: 41,
            },
            {
                codigo: "IMC_GESTANTE_41_NORMAL",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 25.1,
                valorFim: 29.2,
                classificacao: "Normal",
                semanaGestacional: 41,
            },
            {
                codigo: "IMC_GESTANTE_41_SOBREPESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 29.3,
                valorFim: 33.2,
                classificacao: "Sobrepeso",
                semanaGestacional: 41,
            },
            {
                codigo: "IMC_GESTANTE_41_OBESIDADE",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 33.3,
                valorFim: 999,
                classificacao: "Obesidade",
                semanaGestacional: 41,
            },
            {
                codigo: "IMC_GESTANTE_42_BAIXO_PESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 0,
                valorFim: 25,
                classificacao: "Baixo Peso",
                semanaGestacional: 42,
            },
            {
                codigo: "IMC_GESTANTE_42_NORMAL",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 25.1,
                valorFim: 29.2,
                classificacao: "Normal",
                semanaGestacional: 42,
            },
            {
                codigo: "IMC_GESTANTE_42_SOBREPESO",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 29.3,
                valorFim: 33.2,
                classificacao: "Sobrepeso",
                semanaGestacional: 42,
            },
            {
                codigo: "IMC_GESTANTE_42_OBESIDADE",
                idadeInicio: 0,
                idadeFim: 0,
                valorInicio: 33.3,
                valorFim: 999,
                classificacao: "Obesidade",
                semanaGestacional: 42,
            }
        ]
    }


}


